<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="MAIN" Id="{a2945148-3502-4861-8d96-4b8191e12331}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Apparatskåp
ASx();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="316" Count="0" />
      <LineId Id="311" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>